### ISSUE TITLE
Makesweet request 

### ISSUE THREAD

**Issue by jay5656** [scrazzz/AliucordPlugins#7]
Is there any way to use a gallery image and not a url?

**Comment by scrazzz** [comment]
The old version of the plugin required you to give an image from your gallery. A lot of people said that they didn't like it and asked me to make an input field where they can just provide the image url. So that's what the plugin does currently.

If you want, I can make the `url` field optional so that you can either enter the image url or choose an image from your gallery.

**Comment by jay5656** [comment]
> The old version of the plugin required you to give an image from your gallery. A lot of people said that they didn't like it and asked me to make an input field where they can just provide the image url. So that's what the plugin does currently.
> 
> If you want, I can make the `url` field optional so that you can either enter the image url or choose an image from your gallery.

I'd really appreciate that, to at least have the option. I understand their concerns for privacy, but in terms of convenience, it's a real pain to take an image and then convert it to a link.

**Comment by scrazzz** [comment]
Yeah sure. I'll do it.

**Comment by scrazzz** [comment]
Hi, I decided to not work on AliucordPlugins anymore since the React Native version will be released very soon. So I won't be adding the feature you requested. Sorry about that.

**Comment by jay5656** [comment]
What is the react native version?

**Comment by scrazzz** [comment]
It's an alpha version of the Discord App. You should ask this in the Aliucord server for more info.
